theme: just-the-docs
title: "JHPC-Quantum Project"
search_enabled: true
color_scheme: "light"

# logo: "/assets/images/jhpcq-logo.png"

collections:
  docs:
    output: true
    permalink: /:collection/:path/

just_the_docs:
  collections:
    docs:
      name: Documentation
      nav_exclude: false

aux_links:
  "JHPC-Quantum GitHub":
    - "https://github.com/jhpc-quantum"
  "JHPC-Quantum Project":
    - "https://jhpc-quantum.org/en"
  "RIKEN R-CCS":
    - "https://www.r-ccs.riken.jp"

# サイドバー階層の深さ
nav_sort: case_sensitive
